Repository elementary/mail, pull requests merged in 2018-10, with the labels that each got.

#247 Fix DBus error warnings
  webkit-extension/Main.vala
Labels: Rewrite

#293 MessageListBox: Add a placeholder when empty
  src/MessageList/MessageListBox.vala
Labels: Bitesize

#282 ComposerWidget: Replace setter body with a property binding
  src/Composer/ComposerWidget.vala
Labels: Bitesize

#267 ConversationListItem: Set use markup on source label
  src/ConversationList/ConversationListItem.vala
Labels: Bitesize

#302 AttachmentButton.vala: Fix deprecated Gtk.Menu.Popup
  src/MessageList/AttachmentButton.vala
Labels: Bitesize

#251 Test with Houston CI
  .travis.yml
Labels: Status: In Progress
