Repository elementary/mail, pull requests merged in 2021-09, with the labels that each got.

#686 Meson: rename daemon and remove config
  data/daemon.desktop
  data/meson.build
Labels: Bitesize

#682 Add Support for the org.freedesktop.portal.Email portal
  src/Composer/ComposerWidget.vala
Labels: Bitesize, Enhancement

#683 Show time in message header
  src/MessageList/MessageListItem.vala
Labels: Bitesize, Enhancement

#702 Avoid storing to "Sent" twice for outlook.com
  data/io.elementary.mail.appdata.xml.in
  src/Backend/Session.vala
Labels: Bitesize, Bug

#699 Release 6.2.0
  data/io.elementary.mail.appdata.xml.in
  meson.build
Labels: Release
